In [ ]:
#RL for beginners
#Q-learning algorithm

In [ ]:
!pip install gym

In [ ]:
##Using OpenAI's Gym environment- Taxi 

In [ ]:
import numpy as np
import gym
import random

In [ ]:
##Creating the environment
env = gym.make('Taxi-v3')
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [ ]:
#defining the Q-table to know our states and actions
states = env.observation_space.n
actions =  env.action_space.n
print("States:", states)
print('Actions:',actions)

States: 500
Actions: 6


In [ ]:
#Initializing our Q-table
Q = np.zeros((states,actions))
print(Q)
print(Q.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(500, 6)


In [ ]:
#define hyperparameters
episodes = 25000  #training
test_episodes  = 100
steps = 200
state_size = env.
alpha = 0.01
gamma  =  0.99

#Exploration parameters
epsilon = 1.0 #exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.001            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [ ]:
#define the epsilon greedy policy
def eps_greedy(Q,state):
  x = random.uniform(0,1)
  if x  >  epsilon:
    action = np.argmax(Q[state])
  else:
    action =  env.action_space.sample()
  
  return action

In [ ]:
for eps in range(episodes):
  state = env.reset()
  step = 0
  done = False

  #reducing epsilon to favour more exploitation
  epsilon  =  min_epsilon  + (min_epsilon+max_epsilon)*np.exp(-decay_rate*eps)

  #steps
  for step in range(steps):
    action  = eps_greedy(Q,state)
    new_state, reward, done, info  = env.step(action)

    # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
    Q[state][action] = Q[state][action]+alpha*(reward+gamma*np.max(Q[new_state])-Q[state][action])

    if done == True:
      break
     
    state =new_state



In [ ]:
import time
rewards =  []
frames = []

for eps in range(test_episodes):
  state =env.reset()
  step = 0
  done = False
  total_rewrds = 0
  print("*********************************************")
  print("EPISODE:",eps)
  for step in range(steps):
    env.render()
    # Take the action (index) that have the maximum expected future reward given that state
    action = np.argmax(Q[state][:])
    new_state, reward, done, info =  env.step(action)
    total_rewrds+=reward

    if done:
      rewards.append(total_rewrds)
      print ("Score", total_rewrds)
      break
    state =  new_state

env.close()
print ("Score over time: " +  str(sum(rewards)/test_episodes))


Streaming output truncated to the last 5000 lines.
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Score 11
*********************************************
EPISODE: 52
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Score 15
*********************************************
EPISODE: 53
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+